name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test
      - name: Upload WDIO logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: wdio-logs
          path: ${{ github.workspace }}/test/logs/
          if-no-files-found: ignore
          retention-days: 7
